#!/bin/bash


if [[ ! -e "autogit.config" ]]; then
			#config doesn't exist
			echo "WARNING: Couldn't find configuration file (autogit.config). Creating new configuration file."
			touch autogit.config
fi

## escape if on first run
case "$1" in
	"add")
		CURRENT_CONTENTS="$(grep "$2:*" autogit.config)"
		if [ -z "$CURRENT_CONTENTS" ]; then
			echo "$2:$3" >> autogit.config
 		 	echo "the $2 directory will now autogit every $3 hours"
		else
			echo "$2 is already being tracked by autogit and is updated every $(echo ${CURRENT_CONTENTS##*:}) hours."
			read -p "Would you like to change the frequency of the update? (y/n)"
			if [ "y" = $REPLY ]; then
				read -p "How many hours should pass between updates?"
				echo $REPLY

				if [[ $REPLY =~ ^[0-9][0-9] ]]; then
					echo "is number"
				else
					echo "is not a number"
				fi
			elif [ "n" = $REPLY ]; then
				echo "nope"
			fi

		fi
		;;
	"remove")
		echo removing
		if [[ $(grep "$2" ./.autogit.config) ]] ; then
			echo yup
		fi
		;;
	"settings")
			echo "set"
		;;
	"now")
			echo "now"
		;;
		"")
			echo "Welcome to AutoGit!"
		;;
esac
